import type { Metadata } from "next";
import Script from 'next/script'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script strategy='beforeInteractive' src='wasm_exec.js' />
      <body>{children}</body>
    </html>
  );
}
